export const products = [
    {
        id: '1',
        image: 'awm-taiji-tumb.ea5ac88.png',
        title: 'AWP | Oni Taiji',
        price: '643.00',
    },
    {
        id: '2',
        image: 'driver-gloves-convoy-tumb.cd8b220.png',
        title: 'Driver Gloves | Convoy',
        price: '74.80',
    },
    {
        id: '3',
        image: 'negev-anodized-navy-tumb.976d6b0.png',
        title: 'Negev | Anodized Navy',
        price: '630.00',
    },
    {
        id: '4',
        image: 'statTrak-doppler-tumb.08f83e4.png',
        title: 'StatTrak™ Navaja Knife | Doppler',
        price: '630.00',
    },
    {
        id: '5',
        image: 'driver-gloves-tumb.c6b72e3.png',
        title: 'Driver Gloves | Overtake',
        price: '36.80',
    },
    {
        id: '6',
        image: 'aug-hot-rog-tumb.c026509.png',
        title: 'AUG | Hot Rod',
        price: '635.00',
    },
    {
        id: '7',
        image: 'm4a1-printstream-tumb.15b5eae.png',
        title: 'M4A1-S | Printstream',
        price: '574.21',
    },
    {
        id: '8',
        image: 'desert-eagle-printstream-tumb.3c79e54.png',
        title: 'Desert Eagle | Printstream',
        price: '62.52',
    },
    {
        id: '9',
        image: 'huntsman-case-hardened-tumb.e9c8308.png',
        title: 'Huntsman Knife | Case Hardened',
        price: '563.76',
    },
    {
        id: '10',
        image: 'ak-47-asiimov-tumb.61d3b6a.png',
        title: 'AK-47 | Asiimov',
        price: '13.87',
    },
    {
        id: '11',
        image: 'bayonet-doppler-tumb.83aa1d8.png',
        title: 'Bayonet | Doppler Phase 1',
        price: '310.39',
    },
    {
        id: '12',
        image: 'ak-47-frontside-tumb.143388b.png',
        title: 'AK-47 | Frontside Misty',
        price: '17.17',
    },
    {
        id: '13',
        image: 'ak-47-case-hardened-tumb.f97e102.png',
        title: 'AK-47 | Case Hardened',
        price: '65.88',
    },
    {
        id: '14',
        image: 'desert-eagle-discipline-tumb.a2f0c00.png',
        title: 'Desert Eagle | Trigger Discipline',
        price: '5.12',
    },
    {
        id: '15',
        image: 'bayonet-autotronic-tumb.6d7d9f4.png',
        title: 'Bayonet | Autotronic',
        price: '33.00',
    },
    {
        id: '16',
        image: 'bowie-damascus-tumb.c78179c.png',
        title: 'Bowie Knife | Damascus Steel',
        price: '88.96',
    },
    {
        id: '17',
        image: 'bayonet-blue-steel-tumb.d0676c3.png',
        title: 'Bayonet | Blue Steel',
        price: '42.30',
    },
    {
        id: '18',
        image: 'ak-47-emerald-pinstripe-tumb.74ad755.png',
        title: 'AK-47 | Emerald Pinstripe',
        price: '10.29',
    },
    {
        id: '19',
        image: 'ak-47-elite-build-tumb.6c16c80.png',
        title: 'AK-47 | Elite Build ',
        price: '4.10',
    },
    {
        id: '20',
        image: 'desert-eagle-mudder-tumb.e9c109d.png',
        title: 'Desert Eagle | Mudder',
        price: '1',
    },
    {
        id: '21',
        image: 'ak-47-baroque-purple-tumb.48c77e5.png',
        title: 'AK-47 | Baroque Purple',
        price: '3.48',
    },
    {
        id: '22',
        image: 'desert-eagle-midnight-storm-tumb.444ef66.png',
        title: 'Desert Eagle | Midnight Storm',
        price: '11.82',
    },
    {
        id: '23',
        image: 'ak-47-bloodsport-tumb.bfd9f64.png',
        title: 'AK-47 | Bloodsport',
        price: '47.46',
    },
    {
        id: '24',
        image: 'ak-47-aquamarine-tumb.1c75306.png',
        title: 'AK-47 | Aquamarine Revenge',
        price: '25.88',
    },
];
